// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Initialize the Dart DL API and store the SendPort native handle for the touch
/// event push channel. Call once at startup with the pointer from
/// `NativeApi.initializeApiDLData`.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int64)>()
external void pv_init(ffi.Pointer<ffi.Void> api_data, int send_port);

/// Open the panel device and start the worker from a JSON config blob.
/// Returns 0 on success; -1 bad config, -2 already open, -3 device/setup failure,
/// -4 unauthorized device (hardware attestation failed or unsupported -- the
/// device is not, provably, genuine pico-view hardware).
@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>()
external int pv_open(ffi.Pointer<ffi.Uint8> cfg_ptr, int cfg_len);

/// Push one RGBA8888 frame (len == width*height*4) to the panel. Fire-and-forget.
/// Returns 0 if enqueued; -1 no device open; -2 enqueue failed.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external int pv_lcd_flush(
  ffi.Pointer<ffi.Uint8> rgba_ptr,
  int len,
  int width,
  int height,
);

/// Stream a signed firmware image to the device and commit it. Fire-and-forget:
/// progress/result arrive as `"type":"ota"` JSON events on the pv_init SendPort.
/// Returns 0 if enqueued; -1 no device open / null pointer; -2 enqueue failed.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>()
external int pv_ota_start(ffi.Pointer<ffi.Uint8> img_ptr, int len);

/// Ask the device to reboot into its factory recovery image.
/// Returns 0 if enqueued; -1 no device open; -2 enqueue failed.
@ffi.Native<ffi.Int32 Function()>()
external int pv_enter_recovery();

/// Stop the worker and close the device. Idempotent. Returns 0.
@ffi.Native<ffi.Int32 Function()>()
external int pv_close();

/// Start the host system sampler. Idempotent. Returns 0.
@ffi.Native<ffi.Int32 Function()>()
external int pv_sys_open();

/// Sample host telemetry once. Returns a newly-allocated, NUL-terminated UTF-8
/// JSON string that the caller MUST free with pv_sys_free, or null on failure.
/// Opens the sampler on first use.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> pv_sys_sample();

/// Free a string returned by pv_sys_sample. Null is a no-op.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void pv_sys_free(ffi.Pointer<ffi.Char> ptr);

/// Stop the host sampler and free its state. Idempotent. Returns 0.
@ffi.Native<ffi.Int32 Function()>()
external int pv_sys_close();
