// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Initialize the Dart DL API and store the SendPort native handle for the touch
/// event push channel. Call once at startup with the pointer from
/// `NativeApi.initializeApiDLData`.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int64)>()
external void pv_init(ffi.Pointer<ffi.Void> api_data, int send_port);

/// Open the CH347 device and start the worker from a JSON config blob.
/// Returns 0 on success; -1 bad config, -2 already open, -3 device/setup failure.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>()
external int pv_open(ffi.Pointer<ffi.Uint8> cfg_ptr, int cfg_len);

/// Push one RGBA8888 frame (len == width*height*4) to the panel. Fire-and-forget.
/// Returns 0 if enqueued; -1 no device open; -2 enqueue failed.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external int pv_lcd_flush(
  ffi.Pointer<ffi.Uint8> rgba_ptr,
  int len,
  int width,
  int height,
);

/// Stop the worker and close the device. Idempotent. Returns 0.
@ffi.Native<ffi.Int32 Function()>()
external int pv_close();
